import { parseSchedule } from "./lib/parser.js";
import { renderGrid } from "./grid.js";
import { renderWarnings } from "./grid.js";
import { findConflicts } from "./conflicts.js";
const response = await fetch("../fixtures/quarter-capture.json");
const raw = await response.json();
const sections = parseSchedule(raw);
const conflicts = findConflicts(sections);
renderGrid(sections, conflicts);
renderWarnings(sections, conflicts);